
sudo:required

services:
  - docker

before_install:
  - docker build -t peter6z32/udemy-docker-frontend -f Dockerfile.dev .


script:
  - docker run peter6z32/udemy-docker-frontend npm run test -- --coverage

